### ISSUE TITLE
Compress screenshots before upload

### ISSUE THREAD

**Issue by ghost** [chbeer/Jack-Support#10]
I usually do it with ImageOptim before upload.

**Comment by chbeer** [comment]
Why would you do that for iTunes Connect screenshots? Would that help in any ways?

I understand if you do it for your apps assets to minimize the app size, but why for screenshots?

**Comment by ghost** [comment]
First, it make upload faster. Worst case: 5 screenshots per devices, 3 devices and screenshots are localized. So 15 screenshots per languages. I have an app localized in 7 languages so 105 screenshots.

Second, Apple is doing some compression on sended pictures –  I am pretty sure of this reading iTMS logs. I rather do the compression myself to have a better control on final pictures. But maybe I am wrong and pictures still be compressed by iTunes Connect services…

**Comment by chbeer** [comment]
I don't think it's a good idea to compress screenshots before uploading:
- uploading is done by Jack, you don't have to wait for each screenshot
- if Apple is compressing as well, you have double the quality loss (but, honestly I doubt they do)

I'll leave this ticket open for now, as I will be considering it as an option for a future version.

**Comment by ghost** [comment]
OK

But I don’t think a double compression lead to quality loss. For example imageOption can greatly reduce PNG image size and image is not changed after reapply compression on already previously compressed image.

Apple is compressing image :
1. I am pretty sure as I noticed poor screenshots rendering once due to bad compression.
2. As screenshots are served on many devices and forms, compression is mandatory to save huge bandwidth and download time.

**Comment by chbeer** [comment]
Closed as it doesn't make much sense from my point of view.
