### ISSUE TITLE
Need IAP Sorting and Search function

### ISSUE THREAD

**Issue by mattchen** [chbeer/Jack-Support#24]
I have hundreds of IAP in my app, it's a pain to edit them online so I purchased Jack, nice job by the way. But I've found a problem is that when I'm looking for a IAP, it's hard to tell the current sorting rule, is it the default order from apple? There should be a sorting function and also a quick search function would be wonderful.
Thank you.

**Comment by chbeer** [comment]
Hey mattchen,

thank you very much for your input!

What sorting would you prefer? By Product ID, or Reference Name?
For that many IAPs a (real) table view would be way better than what Jack's got now, right?

I'll start by sorting the IAPs by Product ID in the next Bugfix update (1.0.4)

**Comment by chbeer** [comment]
- [x] add search field to IAPs

**Comment by chbeer** [comment]
Done
