### ISSUE TITLE
Added a new version in iTC - can't edit?

### ISSUE THREAD

**Issue by akac** [chbeer/Jack-Support#27]
I created a new version in iTC, but haven't uploaded or prepared to upload yet. However Jack won't let me edit keywords or screenshots. It has a lock icon?

**Comment by chbeer** [comment]
Please post a screenshot. Did you re-download the app data after adding the new version so that Jack loads it?

**Comment by akac** [comment]
Oh yes. Twice. 
![screenshot 2014-04-29 13 09 28](https://cloud.githubusercontent.com/assets/364743/2833545/d3905bc8-cfd1-11e3-9a1b-b0f6f13f06e8.png)
![screenshot 2014-04-29 13 09 08](https://cloud.githubusercontent.com/assets/364743/2833546/d390a65a-cfd1-11e3-8ee8-7c07bfdbff56.png)

**Comment by chbeer** [comment]
Which build number of Jack do you have? (in the About box)
Can you send the document of that app? (in ~/Libraries/Application Support/Jack)

**Comment by akac** [comment]
Version 1.0.4 (53)

Its in the middle of downloading images (taking a really really long time - so far about 30 minutes and I'm on a 100MB connection). It also won't cancel so I think it got stuck. It looks like it had downloaded everything.

https://dl.dropboxusercontent.com/u/9452258/380732176.itmsp.zip

**Comment by chbeer** [comment]
Hm. That's strange, it seems Jack didn't recognize the status of the version. 
It would be very helpful, if you'd do the following:
- Load the NSLogger app from here (if you don’t have it yet): https://github.com/fpillet/NSLogger (there is a binary download, you don’t need to build it yourself)
- enable debuggin in Jack by doing this on the command line:

```
defaults write de.chbeer.osx.tools.Jack CocoaLumberJackLevel verbose
defaults write de.chbeer.osx.tools.Jack CocoaLumberJackDNSLogger -bool true
```

After restarting Jack, please let it run until nothing happens anymore in NSLogger and then please send me the logging by saving it in NSLogger. I'm interested in the part saying "… found details: ..." about the app in question. So you can leave out the rest.

**Comment by akac** [comment]
So…now, its letting me edit in Jack. Only after I ran the logging. Weird.

**Comment by akac** [comment]
https://dl.dropboxusercontent.com/u/9452258/jack.nsloggerdata

**Comment by chbeer** [comment]
Hm. Maybe the restart?

Awesome: NSLogger crashes when opening your file... Ugh!

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (LoggerTCPConnection)'
```

**Comment by chbeer** [comment]
I suppose scraping everything is not a good solution for many apps. I just got around 10 apps and it works fine.

Maybe I need to find a better way.

**Comment by chbeer** [comment]
Was this issue fixed? Do I remember that correctly?
