### ISSUE TITLE
Can't connect to iTunes Connect

### ISSUE THREAD

**Issue by teehemkay** [chbeer/Jack-Support#30]
"Login failed. Please check username and password"
I've double-checked and I'm pretty sure my login and password are correct.

Since password includes special characters maybe it's an encoding issue?

**Comment by chbeer** [comment]
Can you give a hint what kind of "special characters" you're using? Maybe you can tell me one of that characters?

I need to call a JSONRPC API for logging in... would love to test it out to see at which point the encoding fails.

**Comment by teehemkay** [comment]
Hi Christian,

On 1 mai 2014, at 21:25, Christian Beer notifications@github.com wrote:

> Can you give a hint what kind of "special characters" you're using? Maybe you can tell me one of that characters?

Thanks for getting back to me.

Sure I use the following characters: .,?!%$*);=+
Hope this helps.

**Comment by chbeer** [comment]
Trying that exact password (copy and pasted the characters) it works for me. 

I don't see why that wouldn't be encodeable in JSON. Do you maybe use other special characters?

**Comment by teehemkay** [comment]
On 1 mai 2014, at 22:40, Christian Beer notifications@github.com wrote:

> Trying that exact password (copy and pasted the characters) it works for me.
> 
> I don't see why that wouldn't be encodeable in JSON. Do you maybe use other special characters?

Nope those are the only ones I’m using and indeed there’s no reason why they can’t be encoded in a JSON payload.

But now there’s a red wifi-signal-kind of icon that appears both on the sign in dialog and in the main window.
And the “Sign In” button remains greyed out.
I’m no sure what’s that icon indicates but my internet connection is fully functional.

**Comment by teehemkay** [comment]
My Apple ID consist of @mac.com address that has an @me.com alias.

I initially tried to sign in using my @mac.com email address and I got the above error message.

Now I just thought I'd tried with the @me.com email address and guess what, it worked!

This is kind of strange because my true Apple ID is the @mac.com email address.

I just double-checked and I can use either of these email address to sign in the iTunes Connect website.

**Comment by chbeer** [comment]
I suppose this is something I can't do much about. It's the services I use that behave this way... and iTunes Connect can do much more behind the scenes than me.

So I will close this, sorry for your inconveniences.
