### ISSUE TITLE
Can't cancel Sign in

### ISSUE THREAD

**Issue by teehemkay** [chbeer/Jack-Support#31]
When there's a problem signing in, the app is stuck with the Sign in dialog which doesn't allow cancellation.

Even though the Quit menu item is still available it doesn't work.
One has no option but to force-quit the app.

This is a problem because it prevents the from update the app from being update with the auto-update feature
![jack stuck screen shot 2014-05-01 at 13 51 29](https://cloud.githubusercontent.com/assets/4826/2851924/fe064574-d126-11e3-8915-2ec80d298644.png)

**Comment by chbeer** [comment]
I see that this uncancelable login-sheet leads to problems. I will double-check and find a solution.

**Comment by teehemkay** [comment]
On 1 mai 2014, at 21:26, Christian Beer notifications@github.com wrote:

> I see that this uncancelable login-sheet leads to problems. I will double-check and find a solution.

Thanks!

One is _obliged_ to successfully log into iTunes Connect:
If for some reason they can’t then their only option is to force-quit.

**Comment by teehemkay** [comment]
Ooops, just discovered that I could just hit "esc" key to cancel the sign in dialog, <facepalm/>.
