### ISSUE TITLE
German locale error on iTC upload

### ISSUE THREAD

**Issue by shanezilla** [chbeer/Jack-Support#33]
Creating the german locale in Jack, populating it, and then attempting to upload it to iTC errors our. Screenshot attached.
![screen shot 2014-05-03 at 10 10 03 am](https://cloud.githubusercontent.com/assets/141740/2870647/3c25046c-d2d5-11e3-849a-3bccf120d90d.png)

**Comment by chbeer** [comment]
Uh, that's not good. My apps always had "de" as a language. Will check and build an update soon!
