### ISSUE TITLE
Screenshots are not downloaded automatically

### ISSUE THREAD

**Issue by chbeer** [chbeer/Jack-Support#34]
in some occasions, when downloading data from iTunes Connect the screenshots are not loaded (the placeholder with the "Missing" state persist indefinitely); in order to fix the issue you have to close and re-open the app;
– Matteo Lallone

**Comment by muccy** [comment]
Lately the workaround doesn't work. What is more I receive this error every time I open the application.
![schermata 2014-06-19 alle 10 05 55](https://cloud.githubusercontent.com/assets/18466/3324989/8faf1bf4-f788-11e3-8a8a-43daa7890cca.png)

**Comment by chbeer** [comment]
Did you login to iTunes Connect via browser? When I log in, I need to review some agreements. I will improve the parser, so that it recognizes this…

And I will improve the error message to give a hint to check if iTC is not down.

Am 19.06.2014 um 10:06 schrieb Muccy notifications@github.com:

**Comment by muccy** [comment]
Hi. I accepted new agreements many days ago. The only thing has changed in iTunes Connect is "Manage Your Apps" label. It is now localized to Italian "Gestisci le tue app".

**Comment by chbeer** [comment]
Ah, thanks for the hint! Will check that and fix it fast.

Von meinem iPhone gesendet

**Comment by muccy** [comment]
With 1.0.7 update this seems fixed. If I force screenshots download from menu they are displayed correctly.

**Comment by chbeer** [comment]
Working in current version
