### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by cxa** [chbeer/Jack-Support#38]
Failed to upload. Constantly got this as screen shot. My password contains special chars.

![screen shot 2014-05-17 at 23 45 27](https://cloud.githubusercontent.com/assets/32127/3005341/4f1c1c44-ddda-11e3-9dca-480f96e466bd.png)

**Comment by chbeer** [comment]
Hi cxa,

sorry for answering that late. Did miss the notification about this issue.

What are the "special chars" your password contains? Do you maybe have aliases for your Apple-ID?

**Comment by chbeer** [comment]
Closing because it doesn't seem to happen to others. There was a problem with aliases once. Maybe related.
