### ISSUE TITLE
Unable to add images anymore

### ISSUE THREAD

**Issue by pkclsoft** [chbeer/Jack-Support#40]
All was looking fine but tonight when I wanted to actually upload and submit my app, I've just loaded all of the screenshots (3 languages, 3 device sizes) and then duplicated Australian English to English, UK English.

Again, all looked fine on screen, however the upload failed because it couldn't find the images for the original Australian English.  I took a look inside the itms package and sure enough, the images had been duplicated for UK and US English but the AU files were gone.

After this, the app crashed, and now I cannot, for love or money get the Jack to re-download from iTunes after removing the app from the Documents folder.  Opening the app pane shows me everything except images, with no place holders to drag new images.

So my next step is to back up the application support/Jack folder and then remove it, and start over.

**Comment by chbeer** [comment]
Sorry, I somehow missed this ticket. Did you manage to get it working again?

**Comment by pkclsoft** [comment]
Hi Christian,

No.  To be honest, I've removed Jack from my Mac.  I find these days that
with the new ITC, and the need to be able to upload new things like app
previews, etc, that I just don't need Jack anymore.  The drag-drop
interface for image uploads in ITC has made the process much easier, and I
found that Jack was a bit clumsy in this regard in any case.

I think it's a great idea, but I think also that Apple are making your life
difficult by moving the finish line on you all the time.

Regards

Peter Easdown
@pkclsoft

Developer of:

Money Up! - Learn how to use the Next Dollar Up method
http://bit.ly/1yyIXZc
9 Letters http://bit.ly/9LUS
Tap Times Tables http://bit.ly/171Ia3j
Math Plus Minus http://bit.ly/1anwcV8
Crazy Balloons http://bit.ly/1lUlTdj
Crazy Balloons - First Sight Words http://bit.ly/CBFSWIT
Crazy Balloons - Spelling http://bit.ly/CBSpress
Out of Space http://bit.ly/16ZloY4
Cheapskate http://bit.ly/14SwKtT
uAlertMe http://bit.ly/16s7X3T

If you review apps, and would be interested in reviewing any of the above
title, please let me know and I'll provide promo codes.

**Comment by chbeer** [comment]
Ok, sad news. 

Maybe you find a reason to retry Jack sometimes. I'm working on improving it as much as I can... maybe a future version is more helpful.

Best regards,

Christian
