### ISSUE TITLE
Cannot add/change screenshots during update

### ISSUE THREAD

**Issue by muccy** [chbeer/Jack-Support#41]
As I updated to 1.0.7 I cannot add/change/remove screenshot for an app update in "Preparing for update" state. 
Everything is marked as locked as you can see from attached picture.
Bye, thanks.
![schermata 2014-07-23 alle 15 41 26](https://cloud.githubusercontent.com/assets/18466/3673675/21f2c6cc-126f-11e4-9a87-078a26be721b.png)

**Comment by chbeer** [comment]
Hey @muccy, sorry for answering late! In the current version this should be fixed. Please re-open if not.
