### ISSUE TITLE
error uploading

### ISSUE THREAD

**Issue by JumpApp** [chbeer/Jack-Support#47]
Hi,

I am trying to upload the package of screenshots in all sizes and all languages (550 files). I was able to do it few days ago but today I am still getting an error saying: 

"The number of files in the package exceeds the maximum of 250 for the transport Aspera. Please try a different transport. (1134)"

After few tries I tried to upload less screenshots (250) but it failed anyway and the same error appeared. Any thought what to do with that?

**Comment by chbeer** [comment]
Found a solution in deliver: https://github.com/KrauseFx/deliver/issues/77

Will issue an update soon
